spring:
  application:
    name: identity-service
  datasource:
    username: root
    password: Fuokqo1608*
    url: "jdbc:mysql://localhost:3306/identity_service"
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
jwt:
  signerKey: "FbJ8hUwxp2hHXaQFZDAw7XLt+qfUieWI4iDGVV2sJZuWNNUQcBzE4eySv9wUn7LT"
